### ISSUE TITLE
Adapt to use the new OpenFile method from the OpenURI portal

### ISSUE THREAD

**Issue by mariospr** [flatpak/flatpak-xdg-utils#1]
As part of https://github.com/flatpak/xdg-desktop-portal/pull/105, and to prevent a security issue where the sandbox could be escaped at a filesystem level, the OpenURI method of this portal stopped handling `file://` URIs, meaning that external files now must be accessed either via the documents portal or by using a local the newly added `OpenFile` method, which accepts a file descriptor instead of the URI.

From what I can see in https://github.com/flatpak/flatpak-xdg-utils/blob/master/src/xdg-open.c, this implementation of xdg-open does not treat native and non-native URIs differently (they all go through the OpenURI portal), so this would need to be adapted for `file://` URIs to continue working

**Comment by matthiasclasen** [comment]
This is probably best done by borrowing the gopenuriportal.c file that I added in glib for this.

**Comment by matthiasclasen** [comment]
See my PR

**Comment by fmuellner** [comment]
The PR has been merged.
