### ISSUE TITLE
xdg-email doesn't seem to support `mailto:` URLs

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak-xdg-utils#19]
The reference xdg-email(1) is documented as accepting these as equivalent:

    xdg-email --subject="Make Money Fast" --body="Spam" me@example.com
    xdg-email "mailto:me@example.com?subject=Make%20Money%20Fast&body=Spam"

but I don't see any code in xdg-email to handle the latter.

**Comment by matthiasclasen** [comment]
Do you know of users in the wild using a mailto: url for xdg-email ?

**Comment by smcv** [comment]
The documentation and `--help` were my only reference, but https://codesearch.debian.net/search?q=xdg-email.*mailto%3A says jami (formerly ring) also uses `mailto:`.

**Comment by jhenstridge** [comment]
For what it is worth, Chromium also calls xdg-email with a mailto: URI:

https://github.com/chromium/chromium/blob/master/chrome/browser/platform_util_linux.cc#L187

So that probably extends to some Electron apps too.
