### ISSUE TITLE
Doesn't provide xdg-icon-resource or xdg-desktop-menu

### ISSUE THREAD

**Issue by wjt** [flatpak/flatpak-xdg-utils#35]
I am attempting to update the Tuxpaint Flatpak. The latest version uses these two tools to install icons & desktop files to the correct locations; however, they are not available in the SDK.

Of course, I can install (and clean up) the real ones. But perhaps providing the latter would be a way to, in future, support applications exporting new desktop files at runtime?

**Comment by TingPing** [comment]
Until such a portal exists I see no reason for those tools to exist here.

**Comment by wjt** [comment]
The runtime portal use case was secondary, in my mind. The primary goal was:

- Upstream build system uses `xdg-icon-resource` to install icons and `xdg-desktop-menu` to install desktop file
- I want to avoid patching the upstream build system
- Building these tools from the real `xdg-utils` doesn't work because their behaviour changes based on whether they're run as root or not: as root, they install to system-wide directories, but Flatpak builds don't run as root

So I gave up and patched the build system to use `install`. I don't know how widespread usage of these is in build scripts – probably not very.

**Comment by Mailaender** [comment]
Transcribe and SameBoy use these commands as well. Instead of patching you can also compile your own `xdg-utils`.

**Comment by Mailaender** [comment]
Nevermind it doesn't work:
> xdg-desktop-menu install --novendor --mode system FreeDesktop/sameboy.desktop
xdg-desktop-menu: No writable system menu directory found.
make: [Makefile:508: install] Error 3 (ignored)
