### ISSUE TITLE
--sandbox-expose-path-ro doesn't handle accents

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak-xdg-utils#44]
This works:
```
$ flatpak-spawn  --env=GIO_USE_VFS=local --env=G_MESSAGES_DEBUG=all --sandbox-expose-path=/home/hadess/.var/app/org.gnome.Books/cache/gnome-desktop-thumbnailer/gstreamer-1.0 --env=GST_REGISTRY_1_0=/home/hadess/.var/app/org.gnome.Books/cache/gnome-desktop-thumbnailer/gstreamer-1.0/gstreamer-1.0.registry --watch-bus --sandbox --no-network --sandbox-expose-path=/home/hadess/.var/app/org.gnome.Books/sandbox/gnome-desktop-thumbnailer-9NAMZ0 --sandbox-expose-path-ro="/home/hadess/Documents/e-Books tests/Pepper___Carrot_-_épisodes_13_-_webp.cbz" ls
```
but this fails:
```
$ flatpak-spawn --clear-env --env=LANG=en_GB.UTF-8  --env=GIO_USE_VFS=local --env=G_MESSAGES_DEBUG=all --sandbox-expose-path=/home/hadess/.var/app/org.gnome.Books/cache/gnome-desktop-thumbnailer/gstreamer-1.0 --env=GST_REGISTRY_1_0=/home/hadess/.var/app/org.gnome.Books/cache/gnome-desktop-thumbnailer/gstreamer-1.0/gstreamer-1.0.registry --watch-bus --sandbox --no-network --sandbox-expose-path=/home/hadess/.var/app/org.gnome.Books/sandbox/gnome-desktop-thumbnailer-9NAMZ0 --sandbox-expose-path-ro="/home/hadess/Documents/e-Books tests/Pepper___Carrot_-_épisodes_13_-_webp.cbz" ls
error: Invalid byte sequence in conversion input
```

**Comment by hadess** [comment]
I don't know exactly who gets booted off the bus, but those should be array of arrays of bytes, not strings. From the [Flatpak Portal XML](https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.portal.Flatpak.xml#L145-L163):
```
             <term>sandbox-expose as</term>
             <term>sandbox-expose-ro as</term>
```

**Comment by alexlarsson** [comment]
Did you figure out which process is failing when iconv:ing the string?

**Comment by alexlarsson** [comment]
But yeah, not great that these are strings...

**Comment by alexlarsson** [comment]
We could tweak the portal to accept both (as this is in a stuffed in a variant), but it would need version checks on the user side...

**Comment by hadess** [comment]
> Did you figure out which process is failing when iconv:ing the string?

Couldn't figure it out. Took me a long while to find why it was failing in the first place...

**Comment by smcv** [comment]
> `Pepper___Carrot_-_épisodes_13_-_webp.cbz`

What bytes are those, on-disk?

> I don't know exactly who gets booted off the bus

Perhaps nobody. `Invalid byte sequence in conversion input` looks like an error message from iconv, not from D-Bus.

**Comment by hadess** [comment]
That's the URI:
```
file:///home/hadess/Documents/e-Books%20tests/Pepper___Carrot_-_%C3%A9pisodes_13_-_webp.cbz
```

**Comment by hadess** [comment]
> Perhaps nobody. `Invalid byte sequence in conversion input` looks like an error message from iconv, not from D-Bus.

I think the error is probably from when somebody's trying to print an error, which means already too late.

**Comment by hadess** [comment]
Finally root caused it:
https://github.com/flatpak/flatpak/pull/4138
