### ISSUE TITLE
Provide an implementation of `xdg-settings`

### ISSUE THREAD

**Issue by alsoGAMER** [flatpak/flatpak-xdg-utils#64]
As also stated in [this](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1583) issue, electron made and chromium based apps need that executable to read/configure various system properties, for example mimetype handling.

**Comment by TingPing** [comment]
Flatpak's do not have permissions to change system settings.

**Comment by alsoGAMER** [comment]
Yeah but this causes issues with said apps, there's an official documented way to obtain the same result manually?

**Comment by TingPing** [comment]
A user can manage associations themselves on the host. Flatpaks are not supposed to have this ability.

**Comment by TingPing** [comment]
> That i know, though i'm asking if the process of doing that is documented somewhere, cause i can't seem to find it in the flatpak documentation.

I don't think `flatpak-xdg-utils` is documented anywhere really. Maybe this could be in the README here, which tools are provided and which aren't.

**Comment by alsoGAMER** [comment]
>I don't think flatpak-xdg-utils is documented anywhere really. Maybe this could be in the README here, which tools are provided and which aren't.

That would be great, if you need someone to do it, let me know!
